# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://thesanctuarycares.com
title: The Sanctuary
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 

copyright: 'Copyright &copy; 2019 The Sanctuary'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/TheSanctuaryTN/
  - title: soundcloud
    url: https://soundcloud.com/thesanctuarytn
  - title: phone
    url: "tel://1-423-444-3558/"
  - title: address
    url: https://goo.gl/maps/XP3L2CAJ68LL8nB76
